import uuid
from sqlalchemy import Column, String, DateTime, ForeignKey, Boolean, Text
from sqlalchemy.orm import declarative_base, relationship
from sqlalchemy.sql import func

Base = declarative_base()

class DatabaseConnection(Base):
    __tablename__ = "database_connections"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    name = Column(String, nullable=False, unique=True)
    engine = Column(String, nullable=False) # e.g., oracle, postgresql
    connection_string = Column(String, nullable=False)
    status = Column(String, default="pending") # pending, onboarded, failed
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    tables = relationship("TableMetadata", back_populates="database", cascade="all, delete-orphan")

class TableMetadata(Base):
    __tablename__ = "table_metadata"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    database_id = Column(String, ForeignKey("database_connections.id"), nullable=False)
    name = Column(String, nullable=False)
    semantic_description = Column(Text, nullable=True) # Generated by LLM
    entity_type = Column(String, nullable=True) # E.g., 'Customer', 'Transaction'
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    database = relationship("DatabaseConnection", back_populates="tables")
    columns = relationship("ColumnMetadata", back_populates="table", cascade="all, delete-orphan")

class ColumnMetadata(Base):
    __tablename__ = "column_metadata"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    table_id = Column(String, ForeignKey("table_metadata.id"), nullable=False)
    name = Column(String, nullable=False)
    data_type = Column(String, nullable=False)
    is_primary_key = Column(Boolean, default=False)
    is_foreign_key = Column(Boolean, default=False)
    foreign_key_reference = Column(String, nullable=True) # Format: table.column
    semantic_description = Column(Text, nullable=True) # Generated by LLM
    
    table = relationship("TableMetadata", back_populates="columns")
